from __future__ import annotations

import base64
import io
import json
from typing import Any
from urllib.parse import quote, unquote, urlencode, urlparse, urlsplit

import qrcode
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey
from qrcode.exceptions import DataOverflowError

from ..config import ServerConfig
from .xui import XUIError, find_client, parse_json_field


def build_connection(server: ServerConfig, inbound: dict[str, Any], email: str) -> dict[str, str]:
    client = find_client(inbound, email)
    if not client:
        raise XUIError(f"Client '{email}' not found")

    protocol = str(inbound.get("protocol", "")).strip().lower()
    raw_host = server.public_host or (urlparse(server.panel_url).hostname or server.ssh_host)
    host = _format_uri_host(str(raw_host).strip())
    port = int(inbound.get("port") or 0)
    if not host:
        raise XUIError("Public server host is not configured")
    if not 1 <= port <= 65535:
        raise XUIError(f"Invalid inbound port: {port}")

    remark = f"{server.name} · {email}"
    stream = parse_json_field(inbound.get("streamSettings"), {})
    if not isinstance(stream, dict):
        stream = {}

    if protocol == "vless":
        uri = _vless_uri(client, host, port, remark, stream)
    elif protocol == "vmess":
        uri = _vmess_uri(client, host, port, remark, stream)
    elif protocol == "trojan":
        uri = _trojan_uri(client, host, port, remark, stream)
    elif protocol == "shadowsocks":
        uri = _shadowsocks_uri(client, host, port, remark, inbound)
    elif protocol in {"hysteria", "hysteria2", "hy2"}:
        uri = _hysteria2_uri(client, host, port, remark, inbound, stream)
    else:
        raise XUIError(f"Connection links for protocol '{protocol}' are not implemented")

    return {"uri": uri, "qr_data_url": _qr_data_url(uri)}


def connection_payload(uri: str) -> dict[str, str]:
    """Build a UI-safe representation around a link generated by 3x-ui."""
    value = str(uri or "").strip()
    if not value or "://" not in value:
        raise XUIError("3x-ui returned an invalid connection link")
    parsed = urlsplit(value)
    protocol = parsed.scheme.lower()
    if protocol not in {"vless", "vmess", "trojan", "ss", "hysteria2", "hy2"}:
        raise XUIError(f"Unsupported connection link protocol '{protocol}'")
    label = unquote(parsed.fragment).strip() if parsed.fragment else protocol.upper()
    return {
        "uri": value,
        "protocol": "hysteria2" if protocol == "hy2" else protocol,
        "label": label or protocol.upper(),
        "qr_data_url": _qr_data_url(value),
    }


def _vless_uri(client: dict[str, Any], host: str, port: int, remark: str, stream: dict[str, Any]) -> str:
    credential = str(client.get("id") or "")
    if not credential:
        raise XUIError("VLESS client UUID is missing")
    network = str(stream.get("network") or "tcp")
    security = str(stream.get("security") or "none")
    query: dict[str, str] = {
        "type": network,
        "security": security,
        "encryption": "none",
    }
    if client.get("flow"):
        query["flow"] = str(client["flow"])
    _add_transport_params(query, network, stream)
    _add_security_params(query, security, stream)
    return f"vless://{quote(credential, safe='')}@{host}:{port}?{urlencode(query)}#{quote(remark)}"


def _trojan_uri(client: dict[str, Any], host: str, port: int, remark: str, stream: dict[str, Any]) -> str:
    password = str(client.get("password") or "")
    if not password:
        raise XUIError("Trojan client password is missing")
    network = str(stream.get("network") or "tcp")
    security = str(stream.get("security") or "tls")
    query: dict[str, str] = {"type": network, "security": security}
    _add_transport_params(query, network, stream)
    _add_security_params(query, security, stream)
    return f"trojan://{quote(password, safe='')}@{host}:{port}?{urlencode(query)}#{quote(remark)}"


def _vmess_uri(client: dict[str, Any], host: str, port: int, remark: str, stream: dict[str, Any]) -> str:
    credential = str(client.get("id") or "")
    if not credential:
        raise XUIError("VMess client UUID is missing")
    network = str(stream.get("network") or "tcp")
    security = str(stream.get("security") or "none")
    vmess: dict[str, Any] = {
        "v": "2",
        "ps": remark,
        "add": host.strip("[]"),
        "port": str(port),
        "id": credential,
        "aid": "0",
        "scy": "auto",
        "net": network,
        "type": "none",
        "host": "",
        "path": "",
        "tls": "tls" if security in {"tls", "reality"} else "",
        "sni": "",
        "fp": "chrome",
    }
    query: dict[str, str] = {}
    _add_transport_params(query, network, stream)
    _add_security_params(query, security, stream)
    vmess["host"] = query.get("host", "")
    vmess["path"] = query.get("path", query.get("serviceName", ""))
    vmess["sni"] = query.get("sni", "")
    vmess["fp"] = query.get("fp", "chrome")
    encoded = base64.urlsafe_b64encode(json.dumps(vmess, ensure_ascii=False).encode()).decode().rstrip("=")
    return f"vmess://{encoded}"


def _shadowsocks_uri(client: dict[str, Any], host: str, port: int, remark: str, inbound: dict[str, Any]) -> str:
    settings = parse_json_field(inbound.get("settings"), {})
    if not isinstance(settings, dict):
        settings = {}
    method = str(client.get("method") or settings.get("method") or "chacha20-ietf-poly1305")
    password = str(client.get("password") or settings.get("password") or "")
    if not password:
        raise XUIError("Shadowsocks client password is missing")
    userinfo = base64.urlsafe_b64encode(f"{method}:{password}".encode()).decode().rstrip("=")
    return f"ss://{userinfo}@{host}:{port}#{quote(remark)}"


def _hysteria2_uri(
    client: dict[str, Any],
    host: str,
    port: int,
    remark: str,
    inbound: dict[str, Any],
    stream: dict[str, Any],
) -> str:
    """Build the standard Hysteria 2 URI.

    3x-ui stores per-client authentication in ``password``. Some imports may
    instead use ``auth``, ``token`` or ``id``; those are accepted as fallbacks.
    An explicit username is included only when the client actually has one.
    The display e-mail is metadata and must not be silently treated as a
    userpass username.
    """

    settings = parse_json_field(inbound.get("settings"), {})
    if not isinstance(settings, dict):
        settings = {}

    password = str(
        client.get("password")
        or client.get("auth")
        or client.get("token")
        or client.get("id")
        or ""
    )
    if not password:
        raise XUIError("Hysteria client authentication data is missing")

    username = str(client.get("username") or client.get("user") or "")
    auth = f"{username}:{password}" if username else password
    encoded_auth = quote(auth, safe="")

    query: dict[str, str] = {}
    tls_settings = stream.get("tlsSettings") if isinstance(stream.get("tlsSettings"), dict) else {}

    sni = _first_value(
        tls_settings.get("serverName"),
        _first_list_item(tls_settings.get("serverNames")),
        _deep_first(stream, {"sni", "serverName"}),
        _deep_first(settings, {"sni", "serverName"}),
    )
    if sni:
        query["sni"] = str(sni)

    insecure = _first_value(
        tls_settings.get("allowInsecure"),
        tls_settings.get("insecure"),
        _deep_first(stream, {"allowInsecure", "insecure"}),
        _deep_first(settings, {"allowInsecure", "insecure"}),
    )
    if _as_bool(insecure):
        query["insecure"] = "1"

    pin = _first_value(
        tls_settings.get("pinSHA256"),
        tls_settings.get("pinSha256"),
        _deep_first(stream, {"pinSHA256", "pinSha256", "pin_sha256"}),
        _deep_first(settings, {"pinSHA256", "pinSha256", "pin_sha256"}),
    )
    if pin:
        query["pinSHA256"] = str(pin)

    obfs_type, obfs_password = _hysteria_obfs(settings, stream)
    if obfs_type and obfs_type.lower() not in {"none", "off", "false"}:
        query["obfs"] = obfs_type
        if obfs_password:
            query["obfs-password"] = obfs_password

    query_string = f"?{urlencode(query)}" if query else ""
    return f"hysteria2://{encoded_auth}@{host}:{port}/{query_string}#{quote(remark)}"


def _hysteria_obfs(*sources: dict[str, Any]) -> tuple[str, str]:
    for source in sources:
        if not isinstance(source, dict):
            continue
        obfs = _deep_first(source, {"obfs"})
        obfs_type = ""
        obfs_password = ""

        if isinstance(obfs, dict):
            obfs_type = str(obfs.get("type") or obfs.get("name") or "")
            typed = obfs.get(obfs_type) if obfs_type else None
            if isinstance(typed, dict):
                obfs_password = str(typed.get("password") or "")
            if not obfs_password:
                obfs_password = str(
                    obfs.get("password")
                    or obfs.get("obfsPassword")
                    or obfs.get("obfs-password")
                    or ""
                )
        elif isinstance(obfs, str):
            obfs_type = obfs

        if not obfs_type:
            obfs_type = str(_deep_first(source, {"obfsType", "obfs-type"}) or "")
        if not obfs_password:
            obfs_password = str(_deep_first(source, {"obfsPassword", "obfs-password"}) or "")

        if obfs_type or obfs_password:
            return obfs_type, obfs_password

    return "", ""


def _add_transport_params(query: dict[str, str], network: str, stream: dict[str, Any]) -> None:
    key = {
        "ws": "wsSettings",
        "grpc": "grpcSettings",
        "httpupgrade": "httpupgradeSettings",
        "xhttp": "xhttpSettings",
        "splithttp": "splithttpSettings",
        "tcp": "tcpSettings",
        "kcp": "kcpSettings",
    }.get(network.lower())
    settings = stream.get(key, {}) if key else {}
    if not isinstance(settings, dict):
        return
    if settings.get("path"):
        query["path"] = str(settings["path"])
    if settings.get("serviceName"):
        query["serviceName"] = str(settings["serviceName"])
        query["mode"] = str(settings.get("multiMode") or settings.get("mode") or "gun")
    headers = settings.get("headers") or {}
    if isinstance(headers, dict) and headers.get("Host"):
        host_value = headers["Host"]
        query["host"] = host_value[0] if isinstance(host_value, list) else str(host_value)
    if settings.get("host"):
        query["host"] = str(settings["host"])


def _add_security_params(query: dict[str, str], security: str, stream: dict[str, Any]) -> None:
    if security == "reality":
        settings = stream.get("realitySettings") or {}
        if not isinstance(settings, dict):
            return
        if settings.get("serverNames"):
            query["sni"] = str(settings["serverNames"][0])
        elif settings.get("serverName"):
            query["sni"] = str(settings["serverName"])
        public_key = settings.get("publicKey") or _reality_public_key(settings.get("privateKey"))
        if public_key:
            query["pbk"] = str(public_key)
        if settings.get("shortIds"):
            query["sid"] = str(settings["shortIds"][0])
        if settings.get("spiderX"):
            query["spx"] = str(settings["spiderX"])
        query["fp"] = str(settings.get("fingerprint") or "chrome")
    elif security == "tls":
        settings = stream.get("tlsSettings") or {}
        if not isinstance(settings, dict):
            return
        if settings.get("serverName"):
            query["sni"] = str(settings["serverName"])
        elif settings.get("serverNames"):
            query["sni"] = str(settings["serverNames"][0])
        query["fp"] = str(settings.get("fingerprint") or "chrome")
        if settings.get("alpn"):
            query["alpn"] = ",".join(map(str, settings["alpn"]))


def _reality_public_key(private_key: Any) -> str:
    if not private_key:
        return ""
    try:
        raw = base64.urlsafe_b64decode(str(private_key) + "=" * (-len(str(private_key)) % 4))
        key = X25519PrivateKey.from_private_bytes(raw)
        public_raw = key.public_key().public_bytes(
            encoding=serialization.Encoding.Raw,
            format=serialization.PublicFormat.Raw,
        )
        return base64.urlsafe_b64encode(public_raw).decode().rstrip("=")
    except (ValueError, TypeError):
        return ""


def _deep_first(value: Any, names: set[str]) -> Any:
    if isinstance(value, dict):
        for key, item in value.items():
            if key in names and item not in (None, "", [], {}):
                return item
        for item in value.values():
            found = _deep_first(item, names)
            if found not in (None, "", [], {}):
                return found
    elif isinstance(value, list):
        for item in value:
            found = _deep_first(item, names)
            if found not in (None, "", [], {}):
                return found
    return None


def _first_list_item(value: Any) -> Any:
    return value[0] if isinstance(value, list) and value else None


def _first_value(*values: Any) -> Any:
    for value in values:
        if value not in (None, "", [], {}):
            return value
    return None


def _as_bool(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return value != 0
    return str(value or "").strip().lower() in {"1", "true", "yes", "on"}


def _format_uri_host(host: str) -> str:
    if not host:
        return ""
    if ":" in host and not host.startswith("["):
        return f"[{host}]"
    return host


def _qr_data_url(value: str) -> str:
    try:
        image = qrcode.make(value, error_correction=qrcode.constants.ERROR_CORRECT_L)
    except DataOverflowError as exc:
        raise XUIError("Connection link is too large to encode as a QR code") from exc
    buffer = io.BytesIO()
    image.save(buffer, format="PNG")
    encoded = base64.b64encode(buffer.getvalue()).decode()
    return f"data:image/png;base64,{encoded}"
