#!/usr/bin/env bash
set -Eeuo pipefail

exec 9>/run/lock/xui-system-update.lock
if ! flock -n 9; then
  echo 'Another system update is already running' >&2
  exit 75
fi

export DEBIAN_FRONTEND=noninteractive
/usr/bin/apt-get update
/usr/bin/apt-get -y --with-new-pkgs -o Dpkg::Options::="--force-confold" upgrade

echo '__SYSTEM_UPDATE__=complete'

if [[ -f /var/run/reboot-required ]]; then
  echo '__REBOOT_REQUIRED__=yes'
else
  echo '__REBOOT_REQUIRED__=no'
fi
